name: widgets_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  animate_do: ^3.3.4
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  go_router: ^14.2.1
  hooks_riverpod: ^2.5.2
  riverpod_annotation: ^2.3.5

dev_dependencies:
  build_runner: ^2.4.12
  custom_lint: ^0.6.5
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.4.3
  riverpod_lint: ^2.3.13

flutter:
  uses-material-design: true

  assets:
    - assets/images/
